base/urls.py
from django.urls import path
from . import views
from django.views.generic import TemplateView


app_name = "base"
urlpatterns = [
    path("", views.HomeView.as_view(), name="home"),
    path("create-workout", views.CreateWorkout.as_view(), name="create_workout"),
    path("login", views.LoginPage.as_view(), name="login"),
    path("logout", views.logoutuser, name="logout"),
    path("register", views.RegisterPage.as_view(), name="register"),
    path("workout-delete/<int:pk>", views.DeleteWorkout.as_view(), name="workout_delete"),
    path("update-workout/<int:pk>", views.UpdateWorkout.as_view(), name="workout_update"),
    path("userprofile/<int:pk>", views.UserProfileView.as_view(), name="userprofile"),
    path("userupdate/<int:pk>", views.UserEditView.as_view(), name="user_edit"),
]

fitnessapp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns

urlpatterns = i18n_patterns(
    path('admin/', admin.site.urls),
    path("", include("base.urls"))
)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

base/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.
class GoalsModel(models.Model):
    goal = models.CharField(max_length=200, null=True)

    def __str__(self):
        return self.goal

class User(AbstractUser):
    email = models.EmailField(unique=False, null=True)
    bio = models.TextField(null=True)
    goal = models.ForeignKey(GoalsModel, on_delete=models.SET_NULL, null=True, blank=True)

    

    pic = models.ImageField(null=True, default='person.svg')

class LoadModel(models.Model):
    load = models.FloatField(null=True)

    def __str__(self):
        return str(self.load)

class SetsModel(models.Model):
    sets = models.IntegerField(null=True)

    def __str__(self):
        return str(self.sets)

class RepsModel(models.Model):
    reps = models.IntegerField(null=True)

    def __str__(self):
        return str(self.reps)



class ExerciseList(models.Model):
    name = models.CharField(max_length=200, null=True)
    def __str__(self):
        return self.name

class Exercise(models.Model):
    name = models.ForeignKey(ExerciseList, blank=True, null=True, on_delete=models.SET_NULL)
    
    
    description = models.TextField(null=True)
    load = models.ForeignKey(LoadModel, blank=True, null=True, on_delete=models.SET_NULL)
    sets = models.ForeignKey(SetsModel, blank=True, null=True, on_delete=models.SET_NULL)
    reps = models.ForeignKey(RepsModel, blank=True, null=True, on_delete=models.SET_NULL)
    def __str__(self):
        return str(self.name)



class Workout(models.Model):
    class Meta:
        ordering = ["-created"]
    title = models.CharField(max_length=200, default="My workout")
    exercises = models.ManyToManyField(Exercise)
    created = models.DateTimeField(auto_now=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    goal = models.ForeignKey(GoalsModel, on_delete=models.SET_NULL, null=True)
    

    def __str__(self):
        return str(self.title)

base/forms.py
from django.contrib.auth.forms import UserCreationForm
from base.models import User, Workout, Exercise
from django import forms
from crispy_bootstrap5.bootstrap5 import FloatingField
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout

class RegisterForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
            super().__init__(*args, **kwargs)
            for fieldname in ['username', 'password1', 'password2']:
                self.fields[fieldname].help_text = None
    class Meta:
        model = User
        fields = ["username", 'password1', 'password2']
        


# class WorkoutForm(forms.ModelForm):
#     class Meta:
#         model = Workout
#         fields = ["title"]

# class ExerciseForm(forms.ModelForm):
#     class Meta:
#         model= Exercise
#         fields = "__all__"

class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ["username", "email", "first_name", "last_name", "bio", "goal", "pic"]
        # def __init__(self, *args, **kwargs):
        #     super(UserForm, self).__init__(*args, **kwargs)
        #     self.helper = FormHelper()
        #     self.helper.layout = Layout(
        #         FloatingField('username'),
        #         FloatingField('email'),  
        #         # Render first_name field with floating label
        #                # Render email field with floating label
        #         # Add more FloatingField for other fields as needed
        #     )
        
    
    def clean_username(self):
        username = self.cleaned_data.get("username")
        # Get the username of the instance (user being edited)
        current_username = self.instance.username if self.instance else None
        # Check if the username already exists for other users
        if User.objects.exclude(username=current_username).filter(username=username).exists():
            raise forms.ValidationError("Username already exists. Please choose a different one.")
        return username
        

base/views.py
from django.shortcuts import render
from django.views import View
from base.models import ExerciseList, SetsModel, RepsModel, LoadModel, Exercise, Workout, User, GoalsModel
from django.shortcuts import redirect, reverse
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.mixins import LoginRequiredMixin
from base.forms import RegisterForm, UserForm
from django.http import HttpResponse
from django.db.models import Q
# Create your views here.

def blank_to_none(value):
    return None if value == "" else value

class LoginPage(View):
    def get(self, request):
        
        if request.user.is_authenticated:
            return redirect("base:home")
        ctx = {"page":"login"}
        return render(request, "base/login.html", ctx)
    
    def post(self, request):
        username = request.POST.get("username").lower()
        password = request.POST.get("password")
        try:
            user = User.objects.get(username=username)
        except:
            messages.error(request, "User does not exist")
        
        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            return redirect("base:home")
        else:
            messages.error(request, "Username or password incorrect")
        ctx = {}
        return redirect("base:login")

class RegisterPage(View):
    def get(self, request):
        
        if request.user.is_authenticated:
            return redirect("base:home")
        form = RegisterForm()
        ctx = {"form":form}
        return render(request, "base/register.html", ctx)
    def post(self, request):
        form = RegisterForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            # user.username = user.username.lower()
            user.save()
            
            login(request, user)
            return redirect("base:home")
        else:
            messages.error(request, "An error occured during registeration!!")
            return(redirect("base:register"))
            

def logoutuser(request):
    logout(request)
    return redirect("base:home")

class HomeView(View):
    template_name = 'base/home.html'
    def get(self, request):
        search = request.GET.get("search") if request.GET.get("search") != None else ''
        if request.GET.get("goal") == None:
            workouts = Workout.objects.filter(
                Q(goal__goal__icontains=search) |
                Q(title__icontains=search) |
                Q(user__username__icontains=search) |
                Q(exercises__name__name__icontains=search)
            ).distinct()
            # workouts = Workout.objects.all()
        else:
            goal = GoalsModel.objects.get(goal=request.GET.get("goal"))
            workouts = Workout.objects.filter(goal=goal.pk).filter(
                Q(goal__goal__icontains=search) |
                Q(title__icontains=search) |
                Q(user__username__icontains=search) |
                Q(exercises__name__name__icontains=search)
            ).distinct()

        
        ctx = {"workouts":workouts}

        return render(request, self.template_name, ctx)

class CreateWorkout(View):
    template_name = 'base/workout_form.html'
    def get(self, request):
        exercises = ExerciseList.objects.all()
        ctx = {"exercises":exercises, "len":1, "goals":GoalsModel.objects.all(), "page":"create"}
        return render(request, self.template_name, ctx)
    
    def post(self, request):
        result = list(request.POST.items())
        exercises = (len(result)-3)/4
        title = request.POST.get("title")
        goal, created = GoalsModel.objects.get_or_create(goal=request.POST.get("goal"))
        workout = Workout.objects.create(title=title, user=request.user, goal=goal)
        for i in range(1, int(exercises)+1):
            
            exercise_name, created = ExerciseList.objects.get_or_create(name=request.POST.get("exercise"+str(i))) 
            sets, created = SetsModel.objects.get_or_create(sets=blank_to_none(request.POST.get("sets"+str(i)))) 
            reps, created = RepsModel.objects.get_or_create(reps=blank_to_none(request.POST.get("reps"+str(i)))) 
            load, created = LoadModel.objects.get_or_create(load=blank_to_none(request.POST.get("load"+str(i)))) 
            description = request.POST.get("description"+str(i))
            exercise = Exercise.objects.create(name=exercise_name, load=load, sets=sets, reps=reps, description=description)
            workout.exercises.add(exercise)


        return redirect("base:home")

class DeleteWorkout(View):
    template_name = "base/delete.html"
    def get(self, request, pk):
        obj = Workout.objects.get(pk=pk)
        ctx = {"obj":obj}
        return render(request, self.template_name, ctx)
    def post(self, request, pk):
        workout = Workout.objects.get(pk=pk)
        workout.delete()
        return redirect("base:home")

class UpdateWorkout(View):
    template_name="base/workout_form.html"
    def get(self, request, pk):
        workout = Workout.objects.get(pk=pk)
        count = len(workout.exercises.all())
        ctx = {"workout":workout, "len":count, "goals":GoalsModel.objects.all(), "exercises":ExerciseList.objects.all()}
        return render(request, self.template_name, ctx)
    def post(self, request, pk):
        workout = Workout.objects.get(pk=pk)
        original_length = len(workout.exercises.all())
        result = list(request.POST.items())
        exercises = (len(result)-3)/4
        workout.title = request.POST.get("title")
        workout.goal, created = GoalsModel.objects.get_or_create(goal=request.POST.get("goal"))
        #Updating part
        for i in range(1, int(original_length)+1):
            exercise = workout.exercises.all()[i-1]
            exercise.name, created = ExerciseList.objects.get_or_create(name=request.POST.get("exercise"+str(i)))
            exercise.sets, created = SetsModel.objects.get_or_create(sets=blank_to_none(request.POST.get("sets"+str(i)))) 
            exercise.reps, created = RepsModel.objects.get_or_create(reps=blank_to_none(request.POST.get("reps"+str(i))))
            exercise.load, created = LoadModel.objects.get_or_create(load=blank_to_none(request.POST.get("load"+str(i))))
            exercise.description = request.POST.get("description"+str(i))
            exercise.save()
        workout.save()  

        #Creating Part
        for i in range(int(original_length)+1, int(exercises)+1):
            
            exercise_name, created = ExerciseList.objects.get_or_create(name=request.POST.get("exercise"+str(i))) 
            sets, created = SetsModel.objects.get_or_create(sets=blank_to_none(request.POST.get("sets"+str(i)))) 
            reps, created = RepsModel.objects.get_or_create(reps=blank_to_none(request.POST.get("reps"+str(i))))
            load, created = LoadModel.objects.get_or_create(load=blank_to_none(request.POST.get("load"+str(i))))
            description = request.POST.get("description"+str(i))
            exercise = Exercise.objects.create(name=exercise_name, load=load, sets=sets, reps=reps, description=description)
            workout.exercises.add(exercise)
        

        return redirect("base:home")

class UserProfileView(View):
    template_name = "base/userprofile.html"
    def get(self, request, pk):
        workouts = Workout.objects.filter(user=pk)
        ctx = {"workouts":workouts, "profileuser":User.objects.get(pk=pk)}
        return render(request, self.template_name, ctx)

class UserEditView(View):
    template_name = "base/profile_form.html"
    
    def get(self, request, pk):
        user = User.objects.get(pk=pk)
        
        form = UserForm(instance=user)
        
        ctx = {"form":form}
        return render(request, self.template_name, ctx)
    
    def post(self, request, pk):
        user = User.objects.get(pk=pk)
        form = UserForm(request.POST, request.FILES, instance=user)
        if not form.is_valid() :
            ctx = {'form' : form}
            messages.error(request, "Form not valid")
            return render(request, self.template_name, ctx)
        else:
            form.save()
            return redirect("base:userprofile", pk=pk)

base/templates/base/delete.html
{% extends 'main.html' %} {% block content %}
<form action="" method="post">
  {% csrf_token %}
  <p>Are you sure you want to delete "{{obj}}"?</p>
  <a class="btn btn-info"href="{{request.META.HTTP_REFERER }}">Go back</a>
  <input class="btn btn-danger" type="submit" value="Confirm" />
</form>
{% endblock %}

base/templates/base/feed.html
{% load i18n %}
{% for workout in workouts %}

<div class="card text-start my-4">
  <div class="card-header">{% translate "Goal" %}: {{ workout.goal }}</div>
  <div class="card-body">
    <h5 class="card-title">{{workout}}</h5>
    {% if workout.user == request.user %}
    <a
      class="btn btn btn-sm bg-danger-subtle"
      href="{% url 'base:workout_delete' workout.pk %}"
      ><i class="bi bi-trash"></i></a
    >
    <a
      class="btn btn btn-sm bg-primary-subtle"
      href="{% url 'base:workout_update' workout.pk %}"
      ><i class="bi bi-pen"></i></a
    >
    {% endif %}
    <div class="my-3">
      {% for exercise in workout.exercises.all %}
      <h6 class="card-text">{{exercise}}</h6>
      {% if exercise.sets.sets != None and exercise.reps.reps != None %}
      <p class="card-text">{{exercise.sets}} x {{exercise.reps}}, {% translate "Load" %}: {{exercise.load}}kg</p>
      {% endif %}
      <p>{{exercise.description}}</p>
      {% endfor %}
    </div>
  </div>
  <div class="card-footer text-body-secondary">
    <a href="{% url 'base:userprofile' workout.user.pk %}"
      >@{{workout.user.username}}</a
    >  {{workout.created|timesince}} ago
  </div>
</div>

{% endfor %}

base/templates/base/home.html
{% extends 'main.html' %}
{% block content %}
{% load i18n %}


<div class="row justify-content-center">
    
    <div class="col-12 col-md-6">
        {% if request.user.is_authenticated %}
        <a class="btn btn-success btn-lg rounded-0 mb-2" href="{% url 'base:create_workout' %}"> <i class="bi bi-plus-lg"></i> {% translate "Create Workout" %}</a>
        {% if request.user.goal != None %}
        <a class = "btn btn-lg text-white bg-secondary rounded-0 mb-2" href="{% url 'base:home' %}?goal={{request.user.goal}}">{% translate "Recommend Workouts" %}</a>
        {% endif %}
        {% endif %}
        {% include 'base/feed.html' %}
    </div>
</div>

<hr>


{% endblock %}

base/templates/base/login.html
{% extends 'main.html' %} {% block content %}
{% load i18n %}
<div>
  <form action="" method="post">
    {% csrf_token %}

    <div class="form-floating mb-3">
      <input type="username" class="form-control" id="floatingInput" name="username">
      <label for="floatingInput">{% translate "Username" %}</label>
    </div>
    <div class="form-floating">
      <input type="password" class="form-control mb-3" id="floatingPassword" placeholder="Password" name="password">
      <label for="floatingPassword">{% translate "Password" %}</label>
    </div>


    <input class="btn btn-primary btn-lg mb-3" type="submit" value="Login" />
  </form>
  <p class="display-6" style="font-size: medium;">{% translate "Haven't Signed up yet?" %} <a href="{% url 'base:register' %}" class="btn btn-info btn-sm rounded-pill text-sm">{% translate "Sign up!" %}</a></p>
  
</div>
{% endblock %}

base/templates/base/navbar.html
{% load i18n %}
<nav class="navbar bg-body-tertiary fixed-top">
    <div class="container-fluid">
      <a class="navbar-brand" href="{%  url 'base:home' %}">Fitness App</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasNavbar" aria-controls="offcanvasNavbar" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="offcanvas offcanvas-end" tabindex="-1" id="offcanvasNavbar" aria-labelledby="offcanvasNavbarLabel">
        <div class="offcanvas-header">
          <h5 class="offcanvas-title" id="offcanvasNavbarLabel">Fitness App</h5>
          <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
        </div>
        <div class="offcanvas-body">
          <ul class="navbar-nav justify-content-end flex-grow-1 pe-3">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{%  url 'base:home' %}">{% translate "Home" %}</a>
            </li>
            {% if request.user.is_authenticated %}
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                {{request.user.username}}
              </a>
              <ul class="dropdown-menu">
                <li><a class="dropdown-item" href="{% url 'base:userprofile' request.user.pk %}">{% translate "My Profile" %}</a></li>
                <li><a class="dropdown-item" href="{% url 'base:user_edit' request.user.pk %}">{% translate "Edit Profile" %}</a></li>
                <li>
                  <hr class="dropdown-divider">
                </li>
                <li><a class="dropdown-item" href="{% url 'base:logout' %}">{% translate "Logout" %}</a></li>
              </ul>
            </li>
            {% else %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'base:login' %}">{% translate "Login" %}</a>
            </li>
            {% endif %}
          </ul>
          <form class="d-flex mt-3" role="search" action="{% url 'base:home' %}" method="get">
            <input class="form-control me-2" type="search" placeholder="Search......" aria-label="Search" name="search">
            <a class="btn btn-outline-success" type="submit" >{% translate "Search" %}</a>
          </form>
        </div>
      </div>
    </div>
  </nav>

base/templates/base/profile_form.html
{% extends 'main.html' %}
{% block content %}
{% load crispy_forms_tags %}

<form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit" value="Submit" class="btn btn-success">
</form>

{% endblock %}

base/templates/base/register.html
{% extends 'main.html' %} {% block content %}
{% load crispy_forms_tags %}
{% load i18n %}
<div>
  <form action="" method="post">
    {% csrf_token %} 
    {{form|crispy}}

    <input type="submit" class="btn btn-success my2" value="{% translate 'Register' %}" />
  </form>
  <p>{% translate "Already have an account?" %}
  <a href="{% url 'base:login' %}" class="btn btn-small btn-info text-sm">{% translate "Login" %}</a>
  </p>
</div>
{% endblock %}

base/templates/base/userprofile.html
{% extends 'main.html' %}
{% load static %}
{% block content %}
<div class="row justify-content-center">
    <div class="col-12 col-md-6">
        <div class="card">
            <div class="row justify-content-center mt-2">
                <div class="col-4"><img src="{% static 'images/' %}{{profileuser.pic}}" class="card-img-top rounded-circle img-thumbnail" alt="alt"></div>

            </div>
            <div class="card-body">
                <h3 class="card-title">{{profileuser.first_name|title}} {{profileuser.last_name|title}}</h3>
                <h6 class="card-subtitle mb-2 text-body-secondary">@{{profileuser.username}}</h4>
              <p class="card-text bg-light rounded-1">{{profileuser.bio}}</p>
            </div>
          </div>
    </div>
</div>
{% include 'base/feed.html' %}
<hr>

{% endblock %}

base/templates/base/workout_form.html
{% extends 'main.html' %} {% block content %}
{% load i18n %}
<form action="" method="post" id="workout_form">
  {% csrf_token %}
  {% if workout %}
    <div class="form-floating mb-3">
      <input type="text" class="form-control" id="floatingInput" name="title" placeholder="Give your workout a cool title!" required value="{{workout.title}}">
      <label for="floatingInput">{% translate "Title" %}</label>
    </div>
    <div class="form-floating mb-3">
      <input type="text" class="form-control" id="floatingGoal" name="goal" placeholder="Give your workout a goal" list="goal_list" value="{{workout.goal}}">
      <label for="floatingGoal">{% translate "Goal" %}</label>
      <datalist id="goal_list">
        <select id="goal_name" class="form-select">
          {% for goal in goals %}
          <option value="{{ goal.goal }}">{{ goal.goal }}</option>
          {% endfor %}
        </select>
      </datalist>
    </div>
  <div id="form_contents" class="row g-1 g-md-3">
  {% for workout_exercise in workout.exercises.all %}
  
    <div class="col-6 col-md-3 form-floating mb-3">
      <input type="text" class="form-control" id="floatingExercise" name="exercise{{forloop.counter}}" placeholder="Exercise" list="exercise_list" value="{{workout_exercise}}">
      <label for="floatingExercise">{% translate "Exercise Name" %}</label>
      <datalist id="exercise_list">
        <select id="exercise_name" class="form-select">
          {% for exercise in exercises %}
          <option value="{{exercise.name}}">{{exercise.name}}</option>
          {% endfor %}
        </select>
      </datalist>
      </div>
    <div class="col-2 form-floating mb-3">
      <input type="text" class="form-control" id="floatingSets" name="sets{{forloop.counter}}" placeholder="sets" value='{{workout_exercise.sets.sets|default_if_none:""}}''>
      <label for="floatingSets" class="form-control-sm">{% translate "Sets" %}</label>
    </div>
    <div class="col-2 form-floating mb-3"><input type="text" class="form-control" id="floatingReps" name="reps{{forloop.counter}}" placeholder="reps" value="{{workout_exercise.reps.reps|default_if_none:''}}">
      <label for="floatingReps" class="form-control-sm">{% translate "Reps" %}</label></div>
    <div class="col-2 form-floating mb-3"><input type="text" class="form-control" id="floatingLoad" name="load{{forloop.counter}}" placeholder="load" value="{{workout_exercise.load.load|default_if_none:''}}">
      <label for="floatingLoad" class="form-control-sm">{% translate "Load" %}</label></div>
    <div class="col-7 col-md-3 form-floating mb-3">
      <textarea class="form-control" name="description{{forloop.counter}}" id="floatingDescription" placeholder="Description" style="height: 100px" value="{{workout_exercise.description}}"></textarea>
      <label for="floatingDescription">{% translate "Description" %}</label>
    </div>   
  
  
    {% endfor %}
  </div>
    {% else %}
    <div class="form-floating mb-3">
      <input type="text" class="form-control" id="floatingTitle" name="title" placeholder="Give your workout a cool title!" required value="{{workout.title}}">
      <label for="floatingTitle">{% translate "Title" %}</label>
    </div>
    <div class="form-floating mb-3">
      <input type="text" class="form-control" id="floatingGoal" name="goal" placeholder="Give your workout a goal" list="goal_list" value="{{workout.goal}}">
      <label for="floatingGoal">{% translate "Goal" %}</label>
      <datalist id="goal_list">
        <select id="goal_name" class="form-select">
          {% for goal in goals %}
          <option value="{{ goal.goal }}">{{ goal.goal }}</option>
          {% endfor %}
        </select>
      </datalist>
    </div>
    
  <div id="form_contents" class="row g-1 g-md-3">
    <div class="col-6 col-md-3 form-floating mb-3">
      <input type="text" class="form-control" id="floatingExercise" name="exercise1" placeholder="Exercise" list="exercise_list" value="{{workout_exercise}}">
      <label for="floatingExercise">{% translate "Exercise Name" %}</label>
      <datalist id="exercise_list">
        <select id="exercise_name" class="form-select">
          {% for exercise in exercises %}
          <option value="{{exercise.name}}">{{exercise.name}}</option>
          {% endfor %}
        </select>
      </datalist>
      </div>
    <div class="col-2 form-floating mb-3">
      <input type="text" class="form-control" id="floatingSets" name="sets1" placeholder="sets" value="{{workout_exercise.sets}}">
      <label for="floatingSets" class="form-control-sm">{% translate "Sets" %}</label>
    </div>
    <div class="col-2 form-floating mb-3"><input type="text" class="form-control" id="floatingReps" name="reps1" placeholder="reps" value="{{workout_exercise.reps}}">
      <label for="floatingReps" class="form-control-sm">{% translate "Reps" %}</label></div>
    <div class="col-2 form-floating mb-3"><input type="text" class="form-control" id="floatingLoad" name="load1" placeholder="load" value="{{workout_exercise.load}}">
      <label for="floatingLoad" class="form-control-sm">{% translate "Load" %}</label></div>
    <div class="col-7 col-md-3 form-floating mb-3">
      <textarea class="form-control" name="description1" id="floatingDescription" placeholder="Description" style="height: 100px" value="{{workout_exercise.description}}"></textarea>
      <label for="floatingDescription">{% translate "Description" %}</label>
    </div>   
  </div>
    {% endif %}
    
  
  <button onclick="addMoreField()" type="button" class="btn btn-warning">{% translate "Add Exercise" %}</button>

  {% if page %}
  <input type="submit" value="{% translate 'Create Workout' %}" class="btn btn-success" />
  {% else %}
  <input type="submit" value="{% translate 'Update Workout' %}" class="btn btn-success" />
  {% endif %}
</form>

<script>
  var counter = "{{ len }}";
  counter = parseInt(counter);
  function addMoreField() {
    counter += 1;
    html = '<div class="col-6 col-md-3 form-floating mb-3">\
      <input type="text" class="form-control" id="floatingExercise" name="exercise'+counter+'" placeholder="Exercise" list="exercise_list" value="{{workout_exercise}}">\
      <label for="floatingExercise">{% translate "Exercise Name" %}</label>\
      <datalist id="exercise_list">\
        <select id="exercise_name" class="form-select">\
          {% for exercise in exercises %}\
          <option value="{{exercise.name}}">{{exercise.name}}</option>\
          {% endfor %}\
        </select>\
      </datalist>\
      </div>\
    <div class="col-2 form-floating mb-3">\
      <input type="text" class="form-control" id="floatingSets" name="sets'+counter+'" placeholder="sets" value="{{workout_exercise.sets}}">\
      <label for="floatingSets" class="form-control-sm">{% translate "Sets" %}</label>\
    </div>\
    <div class="col-2 form-floating mb-3"><input type="text" class="form-control" id="floatingReps" name="reps'+counter+'" placeholder="reps" value="{{workout_exercise.reps}}">\
      <label for="floatingReps" class="form-control-sm">{% translate "Reps" %}</label></div>\
    <div class="col-2 form-floating mb-3"><input type="text" class="form-control" id="floatingLoad" name="load'+counter+'" placeholder="load" value="{{workout_exercise.load}}">\
      <label for="floatingLoad" class="form-control-sm">{% translate "Load" %}</label></div>\
    <div class="col-7 col-md-3 form-floating mb-3">\
      <textarea class="form-control" name="description'+counter+'" id="floatingDescription" placeholder="Description" style="height: 100px" value="{{workout_exercise.description}}"></textarea>\
      <label for="floatingDescription">{% translate "Description" %}</label></div>';
    var targetDiv = document.getElementById("form_contents");
    var tempDiv = document.createElement("div");
    tempDiv.className = "row g-1 g-md-3"
    tempDiv.innerHTML = html;
    targetDiv.appendChild(tempDiv);
  }
</script>

{% endblock %}

base/templates/base/workout_form_new.html
{% extends "main.html" %}

{% block content %}
<div>
    <form action="" method="POST">
      {% csrf_token %}
      {{ workout_form.as_p }}
      {{ exercise_form.as_p }}
      <input type="submit" value="Submit">
      <input type="submit" value="Cancel" onclick="window.location.href='{% url 'base:home' %}'';return false;">
    </form>
</div>
{% endblock %}

base/templates/base/workout_update.html
{% extends 'main.html' %}
{% block content %}

{% for exercise in workout.exercises.all %}
<h1>{{exercise}}</h1>
<h2>{{exercise.load}}</h2>
<h2>{{exercise.sets}}</h2>
<h3>{{ forloop.counter }}</h3>

{% endfor %}

{% endblock %}